branch-defaults:
  master:
    environment: CovidCoughPrediction-env
environment-defaults:
  CovidCoughPrediction-env:
    branch: null
    repository: null
global:
  application_name: covid-cough-prediction
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.9.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
